server:
  port: 6601

spring:
  application:
    name: service-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:6601/eureka
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
